const { SlashCommandBuilder, InteractionCollector } = require("discord.js");

const quotes = [];
quotes.push(`Here, all my doubters can see who is constsntly hacking me to alter the posts/pics i throw up here. Not my fault! Everything ive said about this bunch of fairies is true…including hacking me to alter evidence against them after they have both been turned in to the county attorney for several crimes and notified of upcoming lawsuits against them; and this includes the homosexuals clique of them that peeping tom people im town@Auditing the Police @ShadowOath @Cops In Action using satellites while they pork each other.`)
quotes.push(`Getting drilled in the nuts while driving down the road by cop satellites. Murray KY. If you cant see it its been hacked and photoshopped. Should be a good one untik they get ahold of it. Obviously a chic cop. @Auditing the Police @Cops In Action @ABQPOLICE`)
quotes.push(`Getting drilled in the back of the head by cop cowards with their toys nobody wat hes them using. Theyre attacking me for telling you guys about em. This is how they ‘get someone back’ for being a witness agsinst them. murray KY cops need prison time. If you dont plainly see it then they hacked to photoshop again.`)
quotes.push(`Murray KY coppers and their buds doing their midnight harassment once again by shooting pictures of diff coppers with their faces photoshopped to resemble mine through my ceiling and walls from 20 diff angles so they can try to kill me over time with microwaves from satellite weapons zoomed thru my head and body as i ‘try’ to sleep at night. This has gone on day and night for over 2 straight years since I caught one hacking a girls phone to show himself while naked and masterbaiting. I turned him in and he was deposted from one place to another but not fired like he should have been. He went on to cause more trouble with so many people he would up getting shot. Following this, the ofher corrupt ones decided to screw each other while watching me (2 boys); blackmail a guy; hack to steal money; break into my home to steal pain meds after a spinal fusion surgery; hack my phone to regularly erase or photoshop pics if themselves caught ‘in the act’ of committing felonies; bald handlebar mustache guy busted up my gas pipe in my fireplace then turn my electric off at the box (I watched him on my security cam hammering away at it; this Weatherford guy snuck onto my property to plant an opened vodka bottle under the passenger seat of my truck then ran when i chased him thru the yard back to his personal vehicle. Etc etc on and on for the last five years. It sounds like a ‘vent’ but this is all a part of a Human Rights complaint anyone can look at. I’ll make a lot of money off it soon. 100% truth. Plenty of DOJ complaints made regarding all of it.`)
quotes.push(`Homosexual cops (Weatherford and his bunch) from Murray KY zooming their cameras and satellites on my nuts in my own house minding my own business where he already knows, unless he put them there again, there are no illegal drugs or anything ever in my home and has never been until i caught the cops/Weatherford putting them there0`)
quotes.push(`Murray KY cops targeted this girl. She got put in the hospital where she is this morning. She has rashes bad and major headaches. Detective Weatherford in Murray is so much of a pussy he tries to bully girls. When i caught him planting stuff in my truck i chased him through the yard. He ran for his life like a scared little girl. This here was a major Geneva convention breach in many ways. I saw him last night late watching her. Now shes in the hospital. Yesterday i contacted a Fed Prosecutor over him, so he retaliated by hitting myself and a girl i know. What a pussy!`)
quotes.push(`My nuts…cop has zoomed his face between my legs. How gross is that! Only in Murray KY. Looked like Scotty Deshields again. He does gay crap like that to guys. Never has busted a grape…wanted to be a cop. Have fun in the pen kid. Youve lost your mind.`)
quotes.push(`At work. Literally everywhere i go i gotta deal with a homo cop staring at my nuts all day. If yall cant see this they hacked and photoshopped it. If words are misspelled, they did it. If anything gets altered, they did it. Theyre mad i caught some of their boys having sex with their boys and girls having sex with their girls and some of their wives watching me through their cam connections (i dont blame em). And theyre mad because i turned them in for all of it. I will take a lie detector test any day. If anyone who says you know different, i challenge you to a lie detector test or just sue me for defamation. I got witnesses and I will win that for sure. If i gave a fck about em then id figure out their names. But the fact they have worked here (some) 20 years or close and I couldn’t tell you 2 names shows how much I have thought about em. They have attacked me 3.5 years now and the only name i could tell you is Weatherford, Clere, Scotty Deshields, Mike something or other, and that’s about it. And everyone of those i have caught committing major crimes. Oh yeah, Jody Cash who i got on vid jacking off a zillion times. As i am writing this they switched from my nuts to my head with the zoom in. You causing crimes is called entrapment…and you covering them up by altering evidence is called Obstruction by the way. This is what you’re doing and trying to do. Good luck trying`)
quotes.push(`Cop cam/satellite weapon in Murray KY zooming into my home and purposefully into my nuts. Obsessed psychos!`)
quotes.push(`Some cop in Murray KY zooming thru my window. I catch this bunch all day everyday. I set in motion 32 million in lawsuits against them already and i may not be done. Its so easy to catch em if you think this is happening to you. Iphone 12 max or better, thro it on night vision in a dark room…and you got em. Of course they will hack to photoshop at some point. But if you can, get’em`)
quotes.push(`I come home after one job about to head to another and the Murray KY cops/deputies/jail bunch one of em are zooming this shit through my walls. Why on Earth would any jail worker be allowed to watch anyone outside the jail…its a lawsuit waiting to happen. These walls are plain white. Some of what they’re watching plays like a projector screen on my walls now, but for 2 years my tv picked up their signals and I watched em like a channel then. If they dont photoshop this you will be able to tell its just an outline of cell phones being projected in from the outside. What plays on those is visible inside on walls usually…especially if you have an infrared cam. Caught a few dressing up like girls and meeting up. One looked just like a little plump Dolly Parton except for the full beard. If that boys daddy would have seen him he’d of killed him. U talk about PTSD. Now they aim that crap at my head and nuts all day. So for doing that they get outed here until i can get a lawsuit goin. I see em break one law after another watching innocent people at home mostly filming them while screwing or playin w themselves. It seems theyre addicted to opetating this way, which is illegal in the first place. Nothing is usable in court. If anything comes from it then neither is that. It is local reality tv but people just dont know they are getting filmed every day. Awful! They are getting off on the trying to injure people stuff also. Worst corruption and immoral behalvior i have ever witnessed. Nosey ole Murray people get elected just to watch people. Thats who you voted in Murray KY. And i have noticed around town nobody knows or thinks they do this. If you don’t believe me, go look at how many cars stay parked all day. Do not hire any more cops in Murray elected people. You got way too many and too much nonsense going on now. Use the money for other things.`)
quotes.push(`After taking an hour or so to fill out yet more complaints to the FBI against the Murray KY cops due to a 6 year long harassment and false imprisonment campaign- all for bringing up valid arguments during a campaign season on Facebook and trying to replace some elected officials, along with retaliation for a complaint made agsinst them after witnessing a horrible set of crimes- i hit submit- and the form came back saying it was never filled out. Of course when I looked I caught the Murray KY cops in the act of hacking my phone while I am filling out the forms. In other words, I jist caught the coppers in the act if blocking my attempts to get help from the FBI once again. Long term prison in the future for the ones who did that I hope.`)
quotes.push(`Caught these screwballs zoomed into my house. Should be easy to tell it’s not me. If it’s photoshopped to not look like one of them or to look like me or something else, it isn’t. It’s them projecting two faces or themselves into my house.`)

module.exports = {
	data: new SlashCommandBuilder()
		.setName('schizo_meltdown')
		.setDescription('Grabs a ccrouse14 quote at random.'),
	async execute(interaction) {
		await interaction.reply(quotes[Math.floor(Math.random() * quotes.length + 1)]);
	},
};